import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
// Import task types
import com.bmuschko.gradle.docker.tasks.image.*

plugins {
	id 'org.springframework.boot' version '2.7.7'
	id 'io.spring.dependency-management' version '1.0.15.RELEASE'
	id 'org.jetbrains.kotlin.jvm' version '1.6.21'
	id 'org.jetbrains.kotlin.plugin.spring' version '1.6.21'
	id 'com.bmuschko.docker-spring-boot-application' version '6.7.0'
}

group = 'org.kubernetes'
version = '1.0.1'
sourceCompatibility = '17'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.kafka:spring-kafka'
	runtimeOnly 'org.flywaydb:flyway-core'
	runtimeOnly 'org.postgresql:postgresql'
	implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
	implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	// Source: https://mvnrepository.com/artifact/org.testcontainers/testcontainers
	testImplementation("org.testcontainers:testcontainers:2.0.5")
	testImplementation ("org.testcontainers:junit-jupiter:1.21.4")
	testImplementation ("org.testcontainers:kafka:1.21.4")
}

tasks.withType(KotlinCompile) {
	kotlinOptions {
		freeCompilerArgs = ['-Xjsr305=strict']
		jvmTarget = '17'
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.named('bootJar') {
	launchScript()
}

tasks.named('dockerBuildImage') {

}

tasks.named('dockerPushImage') {

}

docker {
	springBootApplication {
		baseImage = 'eclipse-temurin:17-jre'
		ports = [8080,8081]
		images = ['dtbwije/kubernetes:1.0.3']
	}
}
