database.host=${DB_HOST}
database.name=${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=SSL
spring.kafka.ssl.key-store-location=file:${KAFKA_SSL_KEYSTORE_PATH}
spring.kafka.ssl.key-store-password=${KAFKA_SSL_KEYSTORE_PASSWORD}
spring.kafka.ssl.key-password=${KAFKA_SSL_KEY_PASSWORD:${KAFKA_SSL_KEYSTORE_PASSWORD}}
spring.kafka.ssl.key-store-type=${KAFKA_SSL_KEYSTORE_TYPE:PKCS12}
spring.kafka.ssl.trust-store-location=file:${KAFKA_SSL_TRUSTSTORE_PATH}
spring.kafka.ssl.trust-store-password=${KAFKA_SSL_TRUSTSTORE_PASSWORD}
spring.kafka.ssl.trust-store-type=${KAFKA_SSL_TRUSTSTORE_TYPE:PKCS12}